(function(){
var D=window.ZONQR_DATA||{businesses:[],categories:[],zone:{center:[25.5608,-108.4676]}};
if(window.ZONQR_STORAGE&&window.ZONQR_STORAGE.load){var stored=window.ZONQR_STORAGE.load();if(stored&&stored.businesses)D=stored;}
var businesses=D.businesses||[],categories=D.categories||[],zone=D.zone||{center:[25.5608,-108.4676]};
var userPos=null,cat='all',q='',map=null,markers=null,view='list';
var filters={dist:0,rating:0,sort:'near',open:false,feat:false,promo:false};
var $=function(s){return document.querySelector(s)};
function hav(a,b,c,d){var R=6371e3,p1=a*Math.PI/180,p2=c*Math.PI/180,dp=(c-a)*Math.PI/180,dl=(d-b)*Math.PI/180;var x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function dt(m){return m==null?'':(m<1000?Math.round(m)+' m':(m/1000).toFixed(1)+' km')}
function reviews(id){try{return JSON.parse(localStorage.getItem('zonqr_reviews')||'{}')[id]||[]}catch(e){return[]}}
function saveR(id,r){var a=JSON.parse(localStorage.getItem('zonqr_reviews')||'{}');a[id]=a[id]||[];a[id].unshift(r);localStorage.setItem('zonqr_reviews',JSON.stringify(a))}
function avg(b){var rs=reviews(b.id);if(!rs.length)return b.rating||0;return Math.round(rs.reduce(function(n,x){return n+x.stars},0)/rs.length*10)/10}
function list(){var out=businesses.map(function(b){var c=Object.assign({},b);c.distance=userPos?hav(userPos[0],userPos[1],b.lat,b.lng):hav(zone.center[0],zone.center[1],b.lat,b.lng);return c}).filter(function(b){if(cat!=='all'&&b.category!==cat)return false;if(q){var t=((b.name||'')+' '+(b.description||'')+' '+(b.categoryLabel||'')+' '+(b.address||'')+' '+(b.promo||'')).toLowerCase();if(t.indexOf(q)<0)return false}if(filters.dist&&b.distance>filters.dist)return false;if(filters.rating&&avg(b)<filters.rating)return false;if(filters.feat&&!b.destacado)return false;if(filters.promo&&!(b.promo&&String(b.promo).trim()))return false;if(filters.open){var s=(b.status||'').toLowerCase();if(!(s.indexOf('abierto')>=0||s.indexOf('24')>=0))return false}return true});out.sort(function(a,b){if(filters.sort==='rating')return avg(b)-avg(a);if(filters.sort==='name')return a.name.localeCompare(b.name,'es');return a.distance-b.distance});return out}
function nearestBar(rows){var bar=$('#nearest-bar');if(!bar)return;if(!rows.length){bar.hidden=true;return}var n=rows.reduce(function(a,b){return a.distance<b.distance?a:b});bar.hidden=false;bar.innerHTML=(q?'Lo mas cerca de lo que buscas':'Negocio mas cercano')+': <strong>'+n.name+'</strong> a <strong>'+dt(n.distance)+'</strong> '+(userPos?'de ti':'del centro')+' \u00b7 <button type="button" class="linkish" id="open-nearest">Ver ficha</button>';var btn=$('#open-nearest');if(btn)btn.onclick=function(){open(n.id)}}
function render(){var el=$('#categories');if(el){el.innerHTML=categories.map(function(c){return '<button type="button" data-cat="'+c.id+'" class="'+(c.id===cat?'active':'')+'">'+c.label+'</button>'}).join('');el.querySelectorAll('button').forEach(function(btn){btn.onclick=function(){cat=btn.dataset.cat;render()}})}var rows=list(),box=$('#list-view'),cnt=$('#result-count');if(cnt)cnt.textContent=rows.length+' lugares';nearestBar(rows);if(box){box.innerHTML=rows.map(function(b){var img=(b.photos&&b.photos[0])||'';return '<article class="card-biz" data-id="'+b.id+'">'+(img?'<img src="'+img+'" alt="">':'<div class="ph"></div>')+'<div><h3>'+b.name+(b.destacado?' <span class="tag">Destacado</span>':'')+'</h3><p>'+b.categoryLabel+' \u00b7 \u2605 '+avg(b).toFixed(1)+' \u00b7 '+dt(b.distance)+'</p>'+(b.promo?'<p class="promo">'+b.promo+'</p>':'')+'<p><button type="button" class="btn ghost" data-map="'+b.id+'">En mapa</button></p></div></article>'}).join('')||'<p class="empty">Sin resultados</p>';box.querySelectorAll('.card-biz').forEach(function(n){n.onclick=function(e){if(e.target.getAttribute('data-map')){e.stopPropagation();focusMap(e.target.getAttribute('data-map'));return}open(n.dataset.id)}})}if(view==='map'){initMap();upd()}}
function initMap(){if(typeof L==='undefined')return;if(!map){map=L.map('map').setView(zone.center,15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(map);markers=L.layerGroup().addTo(map);var load=$('#map-loading');if(load)load.classList.add('hidden')}if(map.invalidateSize)map.invalidateSize();upd()}
function upd(){if(!markers)return;markers.clearLayers();var rows=list();rows.forEach(function(b){var m=L.marker([b.lat,b.lng]).addTo(markers);m.bindPopup('<strong>'+b.name+'</strong><br>'+dt(b.distance)+'<br><a href="#" class="pop" data-id="'+b.id+'">Ver detalle</a>');m.on('popupopen',function(){var a=document.querySelector('.pop[data-id="'+b.id+'"]');if(a)a.onclick=function(e){e.preventDefault();open(b.id)}}});if(userPos)L.circleMarker(userPos,{radius:8,color:'#c6ff3d',fillColor:'#c6ff3d',fillOpacity:0.9}).addTo(markers).bindPopup('Tu estas aqui');if(rows.length&&map.fitBounds){var pts=rows.map(function(b){return[b.lat,b.lng]});if(userPos)pts.push(userPos);try{map.fitBounds(pts,{padding:[28,28],maxZoom:16})}catch(e){}}}
function setView(v){view=v;document.querySelectorAll('.view-toggle button').forEach(function(b){b.classList.toggle('active',b.dataset.view===v)});if(v==='list'){$('#list-view').classList.remove('hidden');$('#map-view').classList.remove('active')}else{$('#list-view').classList.add('hidden');$('#map-view').classList.add('active');setTimeout(initMap,50)}}
function focusMap(id){setView('map');setTimeout(function(){var b=businesses.find(function(x){return x.id===id});if(b&&map)map.setView([b.lat,b.lng],17)},80)}
function open(id){var b=businesses.find(function(x){return x.id===id});if(!b)return;var d=userPos?hav(userPos[0],userPos[1],b.lat,b.lng):hav(zone.center[0],zone.center[1],b.lat,b.lng);var rs=reviews(id),ov=$('#modal-overlay'),md=$('#modal-content');md.innerHTML='<button class="modal-close" id="mc">\u00d7</button><h2>'+b.name+'</h2><p>\u2605 '+avg(b).toFixed(1)+' \u00b7 '+dt(d)+' \u00b7 '+(b.status||'')+'</p><p>'+(b.description||'')+'</p>'+(b.promo?'<p class="promo">'+b.promo+'</p>':'')+'<p>'+(b.address||'')+' \u00b7 '+(b.hours||'')+'</p><div class="row"><a class="btn lime" href="https://wa.me/'+b.whatsapp+'" target="_blank">WhatsApp</a><a class="btn ghost" href="https://www.google.com/maps/dir/?api=1&destination='+b.lat+','+b.lng+'" target="_blank">Como llegar</a></div>'+(b.photos||[]).map(function(s){return '<img class="gal" src="'+s+'" alt="">'}).join('')+'<h3>Resenas</h3><form id="rf"><select id="st"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select><input id="rt" placeholder="Tu opinion" required><button class="btn lime" type="submit">Publicar</button></form><div>'+(rs.map(function(r){return '<p>\u2605'+r.stars+' \u2014 '+r.text+'</p>'}).join('')||'<p>Se el primero.</p>')+'</div>';ov.classList.add('open');$('#mc').onclick=function(){ov.classList.remove('open')};$('#rf').onsubmit=function(e){e.preventDefault();saveR(id,{stars:+$('#st').value,text:$('#rt').value});open(id);render()}}
async function applyPos(lat,lng,acc){userPos=[lat,lng];var btn=$('#btn-locate');if(btn)btn.textContent=acc&&acc>80?'Ubicacion aproximada':'Ubicacion activa';render();if(window.ZONQR_GEO&&window.ZONQR_GEO.reverse){try{var place=await window.ZONQR_GEO.reverse(lat,lng);if(place){var badge=document.querySelector('.zone-badge');if(badge)badge.innerHTML='<span class="dot"></span> '+place.label}}catch(e){}}}
function requestLocation(){var btn=$('#btn-locate');if(!navigator.geolocation){if(btn)btn.textContent='GPS no disponible';return}if(btn)btn.textContent='Obteniendo ubicacion...';navigator.geolocation.getCurrentPosition(function(p){applyPos(p.coords.latitude,p.coords.longitude,p.coords.accuracy)},function(err){if(btn)btn.textContent=err&&err.code===1?'Permiso denegado':'Activar ubicacion'},{enableHighAccuracy:true,timeout:12000})}
if($('#search-input'))$('#search-input').addEventListener('input',function(e){q=e.target.value.toLowerCase().trim();render()});
document.querySelectorAll('.view-toggle button').forEach(function(b){b.addEventListener('click',function(){setView(b.dataset.view)})});
if($('#modal-overlay'))$('#modal-overlay').addEventListener('click',function(e){if(e.target.id==='modal-overlay')e.target.classList.remove('open')});
['f-dist','f-rating','f-sort'].forEach(function(id){var el=document.getElementById(id);if(!el)return;el.addEventListener('change',function(){filters.dist=+((document.getElementById('f-dist')||{}).value||0);filters.rating=+((document.getElementById('f-rating')||{}).value||0);filters.sort=(document.getElementById('f-sort')||{}).value||'near';render()})});
document.querySelectorAll('.filter-chip').forEach(function(chip){chip.addEventListener('click',function(){var key=chip.dataset.filter;filters[key]=!filters[key];chip.classList.toggle('on',filters[key]);render()})});
if($('#btn-locate'))$('#btn-locate').addEventListener('click',requestLocation);
if($('#map-me'))$('#map-me').addEventListener('click',function(){requestLocation();if(userPos&&map)map.setView(userPos,16)});
if($('#map-near'))$('#map-near').addEventListener('click',function(){var rows=list();if(rows[0])focusMap(rows[0].id)});
if($('#map-all'))$('#map-all').addEventListener('click',function(){setView('map')});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(function(){});
requestLocation();render();
})();
